// Code generated by Slice Machine. DO NOT EDIT.

import Landing from './Landing';
import LogIn from './LogIn';
import Notification from './Notification';
import Ratings from './Ratings';

export {
	Landing,
	LogIn,
	Notification,
	Ratings,
};

export const components = {
	landing: Landing,
	log_in: LogIn,
	notification: Notification,
	ratings: Ratings,
};
