// Code generated by Slice Machine. DO NOT EDIT.

import FoodCard from './FoodCard';
import Landing from './Landing';
import LogIn from './LogIn';
import Notification from './Notification';
import Ratings from './Ratings';
import SignOut from './SignOut';
import Testimonial from './Testimonial';

export {
	FoodCard,
	Landing,
	LogIn,
	Notification,
	Ratings,
	SignOut,
	Testimonial,
};

export const components = {
	food_card: FoodCard,
	landing: Landing,
	log_in: LogIn,
	notification: Notification,
	ratings: Ratings,
	sign_out: SignOut,
	testimonial: Testimonial,
};
