// Code generated by Slice Machine. DO NOT EDIT.

import Landing from './Landing';
import Notification from './Notification';
import Ratings from './Ratings';

export {
	Landing,
	Notification,
	Ratings,
};

export const components = {
	landing: Landing,
	notification: Notification,
	ratings: Ratings,
};
